/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lambda.dynamo;
import com.amazonaws.regions.Regions;
import com.amazonaws.services.dynamodbv2.AmazonDynamoDB;
import com.amazonaws.services.dynamodbv2.AmazonDynamoDBClientBuilder;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDB;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper;
import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.LambdaLogger;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class Library {
    private DynamoDB dynamoDb;
    private String DYNAMODB_TABLE_NAME = "task";
    private Regions REGION = Regions.US_WEST_2;


    public Task save(Task task){
        final AmazonDynamoDB ddb = AmazonDynamoDBClientBuilder.defaultClient();

        DynamoDBMapper ddbMapper = new DynamoDBMapper(ddb);
        Task newTask = new Task(task.getId(), task.getTitle(), task.getDescription(), task.getStatus(), task.getAssignee());

        if (task.getId() != null){
            Task t = ddbMapper.load(Task.class, task.getId());
            ArrayList<History> oldHistory = t.getHistory();
            newTask.setHistory(oldHistory);
            newTask.addHistory();
        }

        ddbMapper.save(newTask);
        return newTask;
    }
}

